#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="timemaster")]
	public partial class DemoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBinhluan(Binhluan instance);
    partial void UpdateBinhluan(Binhluan instance);
    partial void DeleteBinhluan(Binhluan instance);
    partial void InsertUsername(Username instance);
    partial void UpdateUsername(Username instance);
    partial void DeleteUsername(Username instance);
    partial void InsertLOAITIN(LOAITIN instance);
    partial void UpdateLOAITIN(LOAITIN instance);
    partial void DeleteLOAITIN(LOAITIN instance);
    partial void InsertNOIDUNGTT(NOIDUNGTT instance);
    partial void UpdateNOIDUNGTT(NOIDUNGTT instance);
    partial void DeleteNOIDUNGTT(NOIDUNGTT instance);
    #endregion
		
		public DemoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["timemasterConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DemoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DemoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DemoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DemoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Binhluan> Binhluans
		{
			get
			{
				return this.GetTable<Binhluan>();
			}
		}
		
		public System.Data.Linq.Table<Username> Usernames
		{
			get
			{
				return this.GetTable<Username>();
			}
		}
		
		public System.Data.Linq.Table<LOAITIN> LOAITINs
		{
			get
			{
				return this.GetTable<LOAITIN>();
			}
		}
		
		public System.Data.Linq.Table<NOIDUNGTT> NOIDUNGTTs
		{
			get
			{
				return this.GetTable<NOIDUNGTT>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Username_user")]
		public ISingleResult<Username_userResult> Username_user([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user);
			return ((ISingleResult<Username_userResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lanxem")]
		public int lanxem([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> matin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> lanxem)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), matin, lanxem);
			lanxem = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LOAITIN_delete")]
		public int LOAITIN_delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MATIN", DbType="Int")] System.Nullable<int> mATIN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mATIN);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LOAITIN_insert")]
		public int LOAITIN_insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MATIN", DbType="Int")] System.Nullable<int> mATIN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TD", DbType="NVarChar(50)")] string tD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mATIN, tD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LOAITIN_seclect")]
		public ISingleResult<LOAITIN_seclectResult> LOAITIN_seclect([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MATIN", DbType="Int")] System.Nullable<int> mATIN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mATIN);
			return ((ISingleResult<LOAITIN_seclectResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LOAITIN_seclect_all")]
		public ISingleResult<LOAITIN_seclect_allResult> LOAITIN_seclect_all()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<LOAITIN_seclect_allResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LOAITIN_update")]
		public int LOAITIN_update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MATIN", DbType="Int")] System.Nullable<int> mATIN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TD", DbType="NVarChar(50)")] string tD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mATIN, tD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NOIDUNGTT_DELETE")]
		public int NOIDUNGTT_DELETE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MATIN", DbType="Int")] System.Nullable<int> mATIN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mATIN);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NOIDUNGTT_INSERT")]
		public int NOIDUNGTT_INSERT([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MT", DbType="Int")] System.Nullable<int> mT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MLT", DbType="Int")] System.Nullable<int> mLT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TD", DbType="NVarChar(50)")] string tD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NDTT", DbType="NVarChar(300)")] string nDTT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HA", DbType="NVarChar(250)")] string hA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ND", DbType="NVarChar(1000)")] string nD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NGD", DbType="DateTime")] System.Nullable<System.DateTime> nGD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mT, mLT, tD, nDTT, hA, nD, nGD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NOIDUNGTT_SECLECTHOME")]
		public ISingleResult<NOIDUNGTT_SECLECTHOMEResult> NOIDUNGTT_SECLECTHOME()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<NOIDUNGTT_SECLECTHOMEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NOIDUNGTT_SECLIEC")]
		public ISingleResult<NOIDUNGTT_SECLIECResult> NOIDUNGTT_SECLIEC([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MATIN", DbType="Int")] System.Nullable<int> mATIN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mATIN);
			return ((ISingleResult<NOIDUNGTT_SECLIECResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NOIDUNGTT_SECLIEC_ALL")]
		public ISingleResult<NOIDUNGTT_SECLIEC_ALLResult> NOIDUNGTT_SECLIEC_ALL()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<NOIDUNGTT_SECLIEC_ALLResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NOIDUNGTT_SECLIEC_MLTIN")]
		public ISingleResult<NOIDUNGTT_SECLIEC_MLTINResult> NOIDUNGTT_SECLIEC_MLTIN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MLT", DbType="Int")] System.Nullable<int> mLT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mLT);
			return ((ISingleResult<NOIDUNGTT_SECLIEC_MLTINResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.NOIDUNGTT_update")]
		public int NOIDUNGTT_update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MT", DbType="Int")] System.Nullable<int> mT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MLT", DbType="Int")] System.Nullable<int> mLT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TD", DbType="NVarChar(50)")] string tD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NDTT", DbType="NVarChar(300)")] string nDTT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HA", DbType="NVarChar(250)")] string hA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ND", DbType="NVarChar(1000)")] string nD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NGD", DbType="DateTime")] System.Nullable<System.DateTime> nGD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mT, mLT, tD, nDTT, hA, nD, nGD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ramdom")]
		public ISingleResult<ramdomResult> ramdom()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ramdomResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Solx")]
		public int Solx([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> matin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lanxem)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), matin, lanxem);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Username_delete")]
		public int Username_delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Username_Insert")]
		public int Username_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pass, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string hoten)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user, pass, hoten);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Username_search")]
		public ISingleResult<Username_searchResult> Username_search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user, pass);
			return ((ISingleResult<Username_searchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Username_select")]
		public ISingleResult<Username_selectResult> Username_select([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<Username_selectResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Username_select_all")]
		public ISingleResult<Username_select_allResult> Username_select_all()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Username_select_allResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Username_select_update")]
		public int Username_select_update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User", DbType="NVarChar(50)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string pass, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string ten)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, user, pass, ten);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay")]
		public int lay([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user, id);
			id = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Binhluan_update")]
		public int Binhluan_update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MBl", DbType="Int")] System.Nullable<int> mBl, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ND", DbType="NVarChar(500)")] string nD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MATIN", DbType="Int")] System.Nullable<int> mATIN, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> user)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mBl, nD, mATIN, user);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Binhluan_all")]
		public ISingleResult<Binhluan_allResult> Binhluan_all()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Binhluan_allResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Binhluan_delete")]
		public int Binhluan_delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mabl", DbType="Int")] System.Nullable<int> mabl)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mabl);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Binhluan_Insert")]
		public int Binhluan_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ND", DbType="NVarChar(500)")] string nD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MATIN", DbType="Int")] System.Nullable<int> mATIN, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nD, mATIN, user, ngay);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Binhluan_select")]
		public ISingleResult<Binhluan_selectResult> Binhluan_select([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> mabl)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mabl);
			return ((ISingleResult<Binhluan_selectResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Binhluan_select_matin")]
		public ISingleResult<Binhluan_select_matinResult> Binhluan_select_matin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MATIN", DbType="Int")] System.Nullable<int> mATIN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mATIN);
			return ((ISingleResult<Binhluan_select_matinResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Binhluan_select_top")]
		public ISingleResult<Binhluan_select_topResult> Binhluan_select_top([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MATIN", DbType="Int")] System.Nullable<int> mATIN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mATIN);
			return ((ISingleResult<Binhluan_select_topResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Binhluan")]
	public partial class Binhluan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBL;
		
		private string _Noidung;
		
		private System.Nullable<int> _Matin;
		
		private System.Nullable<int> _Username;
		
		private System.Nullable<System.DateTime> _Ngaydang;
		
		private EntityRef<Username> _Username1;
		
		private EntityRef<NOIDUNGTT> _NOIDUNGTT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBLChanging(int value);
    partial void OnMaBLChanged();
    partial void OnNoidungChanging(string value);
    partial void OnNoidungChanged();
    partial void OnMatinChanging(System.Nullable<int> value);
    partial void OnMatinChanged();
    partial void OnUsernameChanging(System.Nullable<int> value);
    partial void OnUsernameChanged();
    partial void OnNgaydangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaydangChanged();
    #endregion
		
		public Binhluan()
		{
			this._Username1 = default(EntityRef<Username>);
			this._NOIDUNGTT = default(EntityRef<NOIDUNGTT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaBL
		{
			get
			{
				return this._MaBL;
			}
			set
			{
				if ((this._MaBL != value))
				{
					this.OnMaBLChanging(value);
					this.SendPropertyChanging();
					this._MaBL = value;
					this.SendPropertyChanged("MaBL");
					this.OnMaBLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidung", DbType="NVarChar(500)")]
		public string Noidung
		{
			get
			{
				return this._Noidung;
			}
			set
			{
				if ((this._Noidung != value))
				{
					this.OnNoidungChanging(value);
					this.SendPropertyChanging();
					this._Noidung = value;
					this.SendPropertyChanged("Noidung");
					this.OnNoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matin", DbType="Int")]
		public System.Nullable<int> Matin
		{
			get
			{
				return this._Matin;
			}
			set
			{
				if ((this._Matin != value))
				{
					if (this._NOIDUNGTT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMatinChanging(value);
					this.SendPropertyChanging();
					this._Matin = value;
					this.SendPropertyChanged("Matin");
					this.OnMatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="Int")]
		public System.Nullable<int> Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					if (this._Username1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydang
		{
			get
			{
				return this._Ngaydang;
			}
			set
			{
				if ((this._Ngaydang != value))
				{
					this.OnNgaydangChanging(value);
					this.SendPropertyChanging();
					this._Ngaydang = value;
					this.SendPropertyChanged("Ngaydang");
					this.OnNgaydangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Username_Binhluan", Storage="_Username1", ThisKey="Username", OtherKey="IDname", IsForeignKey=true)]
		public Username Username1
		{
			get
			{
				return this._Username1.Entity;
			}
			set
			{
				Username previousValue = this._Username1.Entity;
				if (((previousValue != value) 
							|| (this._Username1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Username1.Entity = null;
						previousValue.Binhluans.Remove(this);
					}
					this._Username1.Entity = value;
					if ((value != null))
					{
						value.Binhluans.Add(this);
						this._Username = value.IDname;
					}
					else
					{
						this._Username = default(Nullable<int>);
					}
					this.SendPropertyChanged("Username1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NOIDUNGTT_Binhluan", Storage="_NOIDUNGTT", ThisKey="Matin", OtherKey="Matin", IsForeignKey=true)]
		public NOIDUNGTT NOIDUNGTT
		{
			get
			{
				return this._NOIDUNGTT.Entity;
			}
			set
			{
				NOIDUNGTT previousValue = this._NOIDUNGTT.Entity;
				if (((previousValue != value) 
							|| (this._NOIDUNGTT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NOIDUNGTT.Entity = null;
						previousValue.Binhluans.Remove(this);
					}
					this._NOIDUNGTT.Entity = value;
					if ((value != null))
					{
						value.Binhluans.Add(this);
						this._Matin = value.Matin;
					}
					else
					{
						this._Matin = default(Nullable<int>);
					}
					this.SendPropertyChanged("NOIDUNGTT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Username")]
	public partial class Username : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDname;
		
		private string _UserName1;
		
		private string _Pass;
		
		private string _Hoten;
		
		private EntitySet<Binhluan> _Binhluans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDnameChanging(int value);
    partial void OnIDnameChanged();
    partial void OnUserName1Changing(string value);
    partial void OnUserName1Changed();
    partial void OnPassChanging(string value);
    partial void OnPassChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    #endregion
		
		public Username()
		{
			this._Binhluans = new EntitySet<Binhluan>(new Action<Binhluan>(this.attach_Binhluans), new Action<Binhluan>(this.detach_Binhluans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDname", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDname
		{
			get
			{
				return this._IDname;
			}
			set
			{
				if ((this._IDname != value))
				{
					this.OnIDnameChanging(value);
					this.SendPropertyChanging();
					this._IDname = value;
					this.SendPropertyChanged("IDname");
					this.OnIDnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="UserName", Storage="_UserName1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName1
		{
			get
			{
				return this._UserName1;
			}
			set
			{
				if ((this._UserName1 != value))
				{
					this.OnUserName1Changing(value);
					this.SendPropertyChanging();
					this._UserName1 = value;
					this.SendPropertyChanged("UserName1");
					this.OnUserName1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="NVarChar(50)")]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this.OnPassChanging(value);
					this.SendPropertyChanging();
					this._Pass = value;
					this.SendPropertyChanged("Pass");
					this.OnPassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Username_Binhluan", Storage="_Binhluans", ThisKey="IDname", OtherKey="Username")]
		public EntitySet<Binhluan> Binhluans
		{
			get
			{
				return this._Binhluans;
			}
			set
			{
				this._Binhluans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Binhluans(Binhluan entity)
		{
			this.SendPropertyChanging();
			entity.Username1 = this;
		}
		
		private void detach_Binhluans(Binhluan entity)
		{
			this.SendPropertyChanging();
			entity.Username1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAITIN")]
	public partial class LOAITIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Maloaitin;
		
		private string _Tieude;
		
		private EntitySet<NOIDUNGTT> _NOIDUNGTTs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaloaitinChanging(int value);
    partial void OnMaloaitinChanged();
    partial void OnTieudeChanging(string value);
    partial void OnTieudeChanged();
    #endregion
		
		public LOAITIN()
		{
			this._NOIDUNGTTs = new EntitySet<NOIDUNGTT>(new Action<NOIDUNGTT>(this.attach_NOIDUNGTTs), new Action<NOIDUNGTT>(this.detach_NOIDUNGTTs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maloaitin", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Maloaitin
		{
			get
			{
				return this._Maloaitin;
			}
			set
			{
				if ((this._Maloaitin != value))
				{
					this.OnMaloaitinChanging(value);
					this.SendPropertyChanging();
					this._Maloaitin = value;
					this.SendPropertyChanged("Maloaitin");
					this.OnMaloaitinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tieude", DbType="NVarChar(50)")]
		public string Tieude
		{
			get
			{
				return this._Tieude;
			}
			set
			{
				if ((this._Tieude != value))
				{
					this.OnTieudeChanging(value);
					this.SendPropertyChanging();
					this._Tieude = value;
					this.SendPropertyChanged("Tieude");
					this.OnTieudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITIN_NOIDUNGTT", Storage="_NOIDUNGTTs", ThisKey="Maloaitin", OtherKey="Maloaitin")]
		public EntitySet<NOIDUNGTT> NOIDUNGTTs
		{
			get
			{
				return this._NOIDUNGTTs;
			}
			set
			{
				this._NOIDUNGTTs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NOIDUNGTTs(NOIDUNGTT entity)
		{
			this.SendPropertyChanging();
			entity.LOAITIN = this;
		}
		
		private void detach_NOIDUNGTTs(NOIDUNGTT entity)
		{
			this.SendPropertyChanging();
			entity.LOAITIN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NOIDUNGTT")]
	public partial class NOIDUNGTT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Matin;
		
		private System.Nullable<int> _Maloaitin;
		
		private string _Tieud;
		
		private string _Noidungtt1;
		
		private string _Hinhanh;
		
		private string _Noidung;
		
		private System.Nullable<System.DateTime> _Ngaydang;
		
		private System.Nullable<int> _Lanxem;
		
		private EntitySet<Binhluan> _Binhluans;
		
		private EntityRef<LOAITIN> _LOAITIN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatinChanging(int value);
    partial void OnMatinChanged();
    partial void OnMaloaitinChanging(System.Nullable<int> value);
    partial void OnMaloaitinChanged();
    partial void OnTieudChanging(string value);
    partial void OnTieudChanged();
    partial void OnNoidungtt1Changing(string value);
    partial void OnNoidungtt1Changed();
    partial void OnHinhanhChanging(string value);
    partial void OnHinhanhChanged();
    partial void OnNoidungChanging(string value);
    partial void OnNoidungChanged();
    partial void OnNgaydangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaydangChanged();
    partial void OnLanxemChanging(System.Nullable<int> value);
    partial void OnLanxemChanged();
    #endregion
		
		public NOIDUNGTT()
		{
			this._Binhluans = new EntitySet<Binhluan>(new Action<Binhluan>(this.attach_Binhluans), new Action<Binhluan>(this.detach_Binhluans));
			this._LOAITIN = default(EntityRef<LOAITIN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matin", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Matin
		{
			get
			{
				return this._Matin;
			}
			set
			{
				if ((this._Matin != value))
				{
					this.OnMatinChanging(value);
					this.SendPropertyChanging();
					this._Matin = value;
					this.SendPropertyChanged("Matin");
					this.OnMatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maloaitin", DbType="Int")]
		public System.Nullable<int> Maloaitin
		{
			get
			{
				return this._Maloaitin;
			}
			set
			{
				if ((this._Maloaitin != value))
				{
					if (this._LOAITIN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaloaitinChanging(value);
					this.SendPropertyChanging();
					this._Maloaitin = value;
					this.SendPropertyChanged("Maloaitin");
					this.OnMaloaitinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tieud", DbType="NVarChar(200)")]
		public string Tieud
		{
			get
			{
				return this._Tieud;
			}
			set
			{
				if ((this._Tieud != value))
				{
					this.OnTieudChanging(value);
					this.SendPropertyChanging();
					this._Tieud = value;
					this.SendPropertyChanged("Tieud");
					this.OnTieudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Noidungtt", Storage="_Noidungtt1", DbType="NVarChar(400)")]
		public string Noidungtt1
		{
			get
			{
				return this._Noidungtt1;
			}
			set
			{
				if ((this._Noidungtt1 != value))
				{
					this.OnNoidungtt1Changing(value);
					this.SendPropertyChanging();
					this._Noidungtt1 = value;
					this.SendPropertyChanged("Noidungtt1");
					this.OnNoidungtt1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinhanh", DbType="NVarChar(MAX)")]
		public string Hinhanh
		{
			get
			{
				return this._Hinhanh;
			}
			set
			{
				if ((this._Hinhanh != value))
				{
					this.OnHinhanhChanging(value);
					this.SendPropertyChanging();
					this._Hinhanh = value;
					this.SendPropertyChanged("Hinhanh");
					this.OnHinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidung", DbType="NVarChar(MAX)")]
		public string Noidung
		{
			get
			{
				return this._Noidung;
			}
			set
			{
				if ((this._Noidung != value))
				{
					this.OnNoidungChanging(value);
					this.SendPropertyChanging();
					this._Noidung = value;
					this.SendPropertyChanged("Noidung");
					this.OnNoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydang
		{
			get
			{
				return this._Ngaydang;
			}
			set
			{
				if ((this._Ngaydang != value))
				{
					this.OnNgaydangChanging(value);
					this.SendPropertyChanging();
					this._Ngaydang = value;
					this.SendPropertyChanged("Ngaydang");
					this.OnNgaydangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lanxem", DbType="Int")]
		public System.Nullable<int> Lanxem
		{
			get
			{
				return this._Lanxem;
			}
			set
			{
				if ((this._Lanxem != value))
				{
					this.OnLanxemChanging(value);
					this.SendPropertyChanging();
					this._Lanxem = value;
					this.SendPropertyChanged("Lanxem");
					this.OnLanxemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NOIDUNGTT_Binhluan", Storage="_Binhluans", ThisKey="Matin", OtherKey="Matin")]
		public EntitySet<Binhluan> Binhluans
		{
			get
			{
				return this._Binhluans;
			}
			set
			{
				this._Binhluans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITIN_NOIDUNGTT", Storage="_LOAITIN", ThisKey="Maloaitin", OtherKey="Maloaitin", IsForeignKey=true)]
		public LOAITIN LOAITIN
		{
			get
			{
				return this._LOAITIN.Entity;
			}
			set
			{
				LOAITIN previousValue = this._LOAITIN.Entity;
				if (((previousValue != value) 
							|| (this._LOAITIN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAITIN.Entity = null;
						previousValue.NOIDUNGTTs.Remove(this);
					}
					this._LOAITIN.Entity = value;
					if ((value != null))
					{
						value.NOIDUNGTTs.Add(this);
						this._Maloaitin = value.Maloaitin;
					}
					else
					{
						this._Maloaitin = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOAITIN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Binhluans(Binhluan entity)
		{
			this.SendPropertyChanging();
			entity.NOIDUNGTT = this;
		}
		
		private void detach_Binhluans(Binhluan entity)
		{
			this.SendPropertyChanging();
			entity.NOIDUNGTT = null;
		}
	}
	
	public partial class Username_userResult
	{
		
		private int _IDname;
		
		private string _UserName;
		
		private string _Pass;
		
		private string _Hoten;
		
		public Username_userResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDname", DbType="Int NOT NULL")]
		public int IDname
		{
			get
			{
				return this._IDname;
			}
			set
			{
				if ((this._IDname != value))
				{
					this._IDname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="NVarChar(50)")]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this._Pass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this._Hoten = value;
				}
			}
		}
	}
	
	public partial class LOAITIN_seclectResult
	{
		
		private int _Maloaitin;
		
		private string _Tieude;
		
		public LOAITIN_seclectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maloaitin", DbType="Int NOT NULL")]
		public int Maloaitin
		{
			get
			{
				return this._Maloaitin;
			}
			set
			{
				if ((this._Maloaitin != value))
				{
					this._Maloaitin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tieude", DbType="NVarChar(50)")]
		public string Tieude
		{
			get
			{
				return this._Tieude;
			}
			set
			{
				if ((this._Tieude != value))
				{
					this._Tieude = value;
				}
			}
		}
	}
	
	public partial class LOAITIN_seclect_allResult
	{
		
		private int _Maloaitin;
		
		private string _Tieude;
		
		public LOAITIN_seclect_allResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maloaitin", DbType="Int NOT NULL")]
		public int Maloaitin
		{
			get
			{
				return this._Maloaitin;
			}
			set
			{
				if ((this._Maloaitin != value))
				{
					this._Maloaitin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tieude", DbType="NVarChar(50)")]
		public string Tieude
		{
			get
			{
				return this._Tieude;
			}
			set
			{
				if ((this._Tieude != value))
				{
					this._Tieude = value;
				}
			}
		}
	}
	
	public partial class NOIDUNGTT_SECLECTHOMEResult
	{
		
		private int _Matin;
		
		private System.Nullable<int> _Maloaitin;
		
		private string _Tieud;
		
		private string _Noidungtt;
		
		private string _Hinhanh;
		
		private string _Noidung;
		
		private System.Nullable<System.DateTime> _Ngaydang;
		
		private System.Nullable<int> _Lanxem;
		
		public NOIDUNGTT_SECLECTHOMEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matin", DbType="Int NOT NULL")]
		public int Matin
		{
			get
			{
				return this._Matin;
			}
			set
			{
				if ((this._Matin != value))
				{
					this._Matin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maloaitin", DbType="Int")]
		public System.Nullable<int> Maloaitin
		{
			get
			{
				return this._Maloaitin;
			}
			set
			{
				if ((this._Maloaitin != value))
				{
					this._Maloaitin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tieud", DbType="NVarChar(200)")]
		public string Tieud
		{
			get
			{
				return this._Tieud;
			}
			set
			{
				if ((this._Tieud != value))
				{
					this._Tieud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidungtt", DbType="NVarChar(400)")]
		public string Noidungtt
		{
			get
			{
				return this._Noidungtt;
			}
			set
			{
				if ((this._Noidungtt != value))
				{
					this._Noidungtt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinhanh", DbType="NVarChar(MAX)")]
		public string Hinhanh
		{
			get
			{
				return this._Hinhanh;
			}
			set
			{
				if ((this._Hinhanh != value))
				{
					this._Hinhanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidung", DbType="NVarChar(MAX)")]
		public string Noidung
		{
			get
			{
				return this._Noidung;
			}
			set
			{
				if ((this._Noidung != value))
				{
					this._Noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydang
		{
			get
			{
				return this._Ngaydang;
			}
			set
			{
				if ((this._Ngaydang != value))
				{
					this._Ngaydang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lanxem", DbType="Int")]
		public System.Nullable<int> Lanxem
		{
			get
			{
				return this._Lanxem;
			}
			set
			{
				if ((this._Lanxem != value))
				{
					this._Lanxem = value;
				}
			}
		}
	}
	
	public partial class NOIDUNGTT_SECLIECResult
	{
		
		private int _Matin;
		
		private System.Nullable<int> _Maloaitin;
		
		private string _Tieud;
		
		private string _Noidungtt;
		
		private string _Hinhanh;
		
		private string _Noidung;
		
		private System.Nullable<System.DateTime> _Ngaydang;
		
		private System.Nullable<int> _Lanxem;
		
		public NOIDUNGTT_SECLIECResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matin", DbType="Int NOT NULL")]
		public int Matin
		{
			get
			{
				return this._Matin;
			}
			set
			{
				if ((this._Matin != value))
				{
					this._Matin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maloaitin", DbType="Int")]
		public System.Nullable<int> Maloaitin
		{
			get
			{
				return this._Maloaitin;
			}
			set
			{
				if ((this._Maloaitin != value))
				{
					this._Maloaitin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tieud", DbType="NVarChar(200)")]
		public string Tieud
		{
			get
			{
				return this._Tieud;
			}
			set
			{
				if ((this._Tieud != value))
				{
					this._Tieud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidungtt", DbType="NVarChar(400)")]
		public string Noidungtt
		{
			get
			{
				return this._Noidungtt;
			}
			set
			{
				if ((this._Noidungtt != value))
				{
					this._Noidungtt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinhanh", DbType="NVarChar(MAX)")]
		public string Hinhanh
		{
			get
			{
				return this._Hinhanh;
			}
			set
			{
				if ((this._Hinhanh != value))
				{
					this._Hinhanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidung", DbType="NVarChar(MAX)")]
		public string Noidung
		{
			get
			{
				return this._Noidung;
			}
			set
			{
				if ((this._Noidung != value))
				{
					this._Noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydang
		{
			get
			{
				return this._Ngaydang;
			}
			set
			{
				if ((this._Ngaydang != value))
				{
					this._Ngaydang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lanxem", DbType="Int")]
		public System.Nullable<int> Lanxem
		{
			get
			{
				return this._Lanxem;
			}
			set
			{
				if ((this._Lanxem != value))
				{
					this._Lanxem = value;
				}
			}
		}
	}
	
	public partial class NOIDUNGTT_SECLIEC_ALLResult
	{
		
		private int _Matin;
		
		private System.Nullable<int> _Maloaitin;
		
		private string _Tieud;
		
		private string _Noidungtt;
		
		private string _Hinhanh;
		
		private string _Noidung;
		
		private System.Nullable<System.DateTime> _Ngaydang;
		
		private System.Nullable<int> _Lanxem;
		
		public NOIDUNGTT_SECLIEC_ALLResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matin", DbType="Int NOT NULL")]
		public int Matin
		{
			get
			{
				return this._Matin;
			}
			set
			{
				if ((this._Matin != value))
				{
					this._Matin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maloaitin", DbType="Int")]
		public System.Nullable<int> Maloaitin
		{
			get
			{
				return this._Maloaitin;
			}
			set
			{
				if ((this._Maloaitin != value))
				{
					this._Maloaitin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tieud", DbType="NVarChar(200)")]
		public string Tieud
		{
			get
			{
				return this._Tieud;
			}
			set
			{
				if ((this._Tieud != value))
				{
					this._Tieud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidungtt", DbType="NVarChar(400)")]
		public string Noidungtt
		{
			get
			{
				return this._Noidungtt;
			}
			set
			{
				if ((this._Noidungtt != value))
				{
					this._Noidungtt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinhanh", DbType="NVarChar(MAX)")]
		public string Hinhanh
		{
			get
			{
				return this._Hinhanh;
			}
			set
			{
				if ((this._Hinhanh != value))
				{
					this._Hinhanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidung", DbType="NVarChar(MAX)")]
		public string Noidung
		{
			get
			{
				return this._Noidung;
			}
			set
			{
				if ((this._Noidung != value))
				{
					this._Noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydang
		{
			get
			{
				return this._Ngaydang;
			}
			set
			{
				if ((this._Ngaydang != value))
				{
					this._Ngaydang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lanxem", DbType="Int")]
		public System.Nullable<int> Lanxem
		{
			get
			{
				return this._Lanxem;
			}
			set
			{
				if ((this._Lanxem != value))
				{
					this._Lanxem = value;
				}
			}
		}
	}
	
	public partial class NOIDUNGTT_SECLIEC_MLTINResult
	{
		
		private int _Matin;
		
		private System.Nullable<int> _Maloaitin;
		
		private string _Tieud;
		
		private string _Noidungtt;
		
		private string _Hinhanh;
		
		private string _Noidung;
		
		private System.Nullable<System.DateTime> _Ngaydang;
		
		private System.Nullable<int> _Lanxem;
		
		public NOIDUNGTT_SECLIEC_MLTINResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matin", DbType="Int NOT NULL")]
		public int Matin
		{
			get
			{
				return this._Matin;
			}
			set
			{
				if ((this._Matin != value))
				{
					this._Matin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maloaitin", DbType="Int")]
		public System.Nullable<int> Maloaitin
		{
			get
			{
				return this._Maloaitin;
			}
			set
			{
				if ((this._Maloaitin != value))
				{
					this._Maloaitin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tieud", DbType="NVarChar(200)")]
		public string Tieud
		{
			get
			{
				return this._Tieud;
			}
			set
			{
				if ((this._Tieud != value))
				{
					this._Tieud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidungtt", DbType="NVarChar(400)")]
		public string Noidungtt
		{
			get
			{
				return this._Noidungtt;
			}
			set
			{
				if ((this._Noidungtt != value))
				{
					this._Noidungtt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinhanh", DbType="NVarChar(MAX)")]
		public string Hinhanh
		{
			get
			{
				return this._Hinhanh;
			}
			set
			{
				if ((this._Hinhanh != value))
				{
					this._Hinhanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidung", DbType="NVarChar(MAX)")]
		public string Noidung
		{
			get
			{
				return this._Noidung;
			}
			set
			{
				if ((this._Noidung != value))
				{
					this._Noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydang
		{
			get
			{
				return this._Ngaydang;
			}
			set
			{
				if ((this._Ngaydang != value))
				{
					this._Ngaydang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lanxem", DbType="Int")]
		public System.Nullable<int> Lanxem
		{
			get
			{
				return this._Lanxem;
			}
			set
			{
				if ((this._Lanxem != value))
				{
					this._Lanxem = value;
				}
			}
		}
	}
	
	public partial class ramdomResult
	{
		
		private int _Matin;
		
		private System.Nullable<int> _Maloaitin;
		
		private string _Tieud;
		
		private string _Noidungtt;
		
		private string _Hinhanh;
		
		private string _Noidung;
		
		private System.Nullable<System.DateTime> _Ngaydang;
		
		private System.Nullable<int> _Lanxem;
		
		public ramdomResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matin", DbType="Int NOT NULL")]
		public int Matin
		{
			get
			{
				return this._Matin;
			}
			set
			{
				if ((this._Matin != value))
				{
					this._Matin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maloaitin", DbType="Int")]
		public System.Nullable<int> Maloaitin
		{
			get
			{
				return this._Maloaitin;
			}
			set
			{
				if ((this._Maloaitin != value))
				{
					this._Maloaitin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tieud", DbType="NVarChar(200)")]
		public string Tieud
		{
			get
			{
				return this._Tieud;
			}
			set
			{
				if ((this._Tieud != value))
				{
					this._Tieud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidungtt", DbType="NVarChar(400)")]
		public string Noidungtt
		{
			get
			{
				return this._Noidungtt;
			}
			set
			{
				if ((this._Noidungtt != value))
				{
					this._Noidungtt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinhanh", DbType="NVarChar(MAX)")]
		public string Hinhanh
		{
			get
			{
				return this._Hinhanh;
			}
			set
			{
				if ((this._Hinhanh != value))
				{
					this._Hinhanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidung", DbType="NVarChar(MAX)")]
		public string Noidung
		{
			get
			{
				return this._Noidung;
			}
			set
			{
				if ((this._Noidung != value))
				{
					this._Noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydang
		{
			get
			{
				return this._Ngaydang;
			}
			set
			{
				if ((this._Ngaydang != value))
				{
					this._Ngaydang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lanxem", DbType="Int")]
		public System.Nullable<int> Lanxem
		{
			get
			{
				return this._Lanxem;
			}
			set
			{
				if ((this._Lanxem != value))
				{
					this._Lanxem = value;
				}
			}
		}
	}
	
	public partial class Username_searchResult
	{
		
		private int _IDname;
		
		private string _UserName;
		
		private string _Pass;
		
		private string _Hoten;
		
		public Username_searchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDname", DbType="Int NOT NULL")]
		public int IDname
		{
			get
			{
				return this._IDname;
			}
			set
			{
				if ((this._IDname != value))
				{
					this._IDname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="NVarChar(50)")]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this._Pass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this._Hoten = value;
				}
			}
		}
	}
	
	public partial class Username_selectResult
	{
		
		private int _IDname;
		
		private string _UserName;
		
		private string _Pass;
		
		private string _Hoten;
		
		public Username_selectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDname", DbType="Int NOT NULL")]
		public int IDname
		{
			get
			{
				return this._IDname;
			}
			set
			{
				if ((this._IDname != value))
				{
					this._IDname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="NVarChar(50)")]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this._Pass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this._Hoten = value;
				}
			}
		}
	}
	
	public partial class Username_select_allResult
	{
		
		private int _IDname;
		
		private string _UserName;
		
		private string _Pass;
		
		private string _Hoten;
		
		public Username_select_allResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDname", DbType="Int NOT NULL")]
		public int IDname
		{
			get
			{
				return this._IDname;
			}
			set
			{
				if ((this._IDname != value))
				{
					this._IDname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="NVarChar(50)")]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this._Pass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this._Hoten = value;
				}
			}
		}
	}
	
	public partial class Binhluan_allResult
	{
		
		private int _MaBL;
		
		private string _Noidung;
		
		private System.Nullable<int> _Matin;
		
		private System.Nullable<int> _Username;
		
		private System.Nullable<System.DateTime> _Ngaydang;
		
		public Binhluan_allResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBL", DbType="Int NOT NULL")]
		public int MaBL
		{
			get
			{
				return this._MaBL;
			}
			set
			{
				if ((this._MaBL != value))
				{
					this._MaBL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidung", DbType="NVarChar(500)")]
		public string Noidung
		{
			get
			{
				return this._Noidung;
			}
			set
			{
				if ((this._Noidung != value))
				{
					this._Noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matin", DbType="Int")]
		public System.Nullable<int> Matin
		{
			get
			{
				return this._Matin;
			}
			set
			{
				if ((this._Matin != value))
				{
					this._Matin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="Int")]
		public System.Nullable<int> Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydang
		{
			get
			{
				return this._Ngaydang;
			}
			set
			{
				if ((this._Ngaydang != value))
				{
					this._Ngaydang = value;
				}
			}
		}
	}
	
	public partial class Binhluan_selectResult
	{
		
		private int _MaBL;
		
		private string _Noidung;
		
		private System.Nullable<int> _Matin;
		
		private System.Nullable<int> _Username;
		
		private System.Nullable<System.DateTime> _Ngaydang;
		
		public Binhluan_selectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBL", DbType="Int NOT NULL")]
		public int MaBL
		{
			get
			{
				return this._MaBL;
			}
			set
			{
				if ((this._MaBL != value))
				{
					this._MaBL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidung", DbType="NVarChar(500)")]
		public string Noidung
		{
			get
			{
				return this._Noidung;
			}
			set
			{
				if ((this._Noidung != value))
				{
					this._Noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matin", DbType="Int")]
		public System.Nullable<int> Matin
		{
			get
			{
				return this._Matin;
			}
			set
			{
				if ((this._Matin != value))
				{
					this._Matin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="Int")]
		public System.Nullable<int> Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydang
		{
			get
			{
				return this._Ngaydang;
			}
			set
			{
				if ((this._Ngaydang != value))
				{
					this._Ngaydang = value;
				}
			}
		}
	}
	
	public partial class Binhluan_select_matinResult
	{
		
		private int _MaBL;
		
		private string _Noidung;
		
		private System.Nullable<int> _Matin;
		
		private System.Nullable<int> _Username;
		
		private System.Nullable<System.DateTime> _Ngaydang;
		
		public Binhluan_select_matinResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBL", DbType="Int NOT NULL")]
		public int MaBL
		{
			get
			{
				return this._MaBL;
			}
			set
			{
				if ((this._MaBL != value))
				{
					this._MaBL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidung", DbType="NVarChar(500)")]
		public string Noidung
		{
			get
			{
				return this._Noidung;
			}
			set
			{
				if ((this._Noidung != value))
				{
					this._Noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matin", DbType="Int")]
		public System.Nullable<int> Matin
		{
			get
			{
				return this._Matin;
			}
			set
			{
				if ((this._Matin != value))
				{
					this._Matin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="Int")]
		public System.Nullable<int> Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydang
		{
			get
			{
				return this._Ngaydang;
			}
			set
			{
				if ((this._Ngaydang != value))
				{
					this._Ngaydang = value;
				}
			}
		}
	}
	
	public partial class Binhluan_select_topResult
	{
		
		private int _MaBL;
		
		private string _Noidung;
		
		private System.Nullable<int> _Matin;
		
		private System.Nullable<int> _Username;
		
		private System.Nullable<System.DateTime> _Ngaydang;
		
		public Binhluan_select_topResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBL", DbType="Int NOT NULL")]
		public int MaBL
		{
			get
			{
				return this._MaBL;
			}
			set
			{
				if ((this._MaBL != value))
				{
					this._MaBL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidung", DbType="NVarChar(500)")]
		public string Noidung
		{
			get
			{
				return this._Noidung;
			}
			set
			{
				if ((this._Noidung != value))
				{
					this._Noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matin", DbType="Int")]
		public System.Nullable<int> Matin
		{
			get
			{
				return this._Matin;
			}
			set
			{
				if ((this._Matin != value))
				{
					this._Matin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="Int")]
		public System.Nullable<int> Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydang
		{
			get
			{
				return this._Ngaydang;
			}
			set
			{
				if ((this._Ngaydang != value))
				{
					this._Ngaydang = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
